FROM python:3.11-slim

WORKDIR /app
RUN echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/10sandbox && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libjpeg-dev zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY . /app

ENV STORAGE_BACKEND=local

CMD ["python", "worker/worker.py"]
